name: Real Estate Market in Nairobi, Kenya.

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  get_and_upload_weather_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

    - name: Run your script
      run: |
        python real_estate.py

    - name: Configure git user
      run: |
        git config --global user.name 'datanerdKE'
        git config --global user.email 'adrianjulius04@gmail.com'

    - name: Commit changes
      run: |
        git commit -m "Updated Real Estate Market Data"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
