name: E-Commerce.

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs twice a day, at midnight and noon

jobs:
  get_and_upload_weather_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

    - name: Run your script
      run: |
        python jumia-scraper-bot.ipynb
